name: 'CI'
on:
  pull_request:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3         # checkout the repo
        with:
          fetch-depth: 0 # checkout all previous commits so we get the tags

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install
          git submodule update --init test/bats
          git submodule update --init test/test_helper/bats-assert
          git submodule update --init test/test_helper/bats-support
          
      - name: Run tests
        run: |
          poetry run test/bats/bin/bats --report-formatter junit test

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: report.xml